server:
  port: 8081

spring:
  multipart:
    max-file-size: 20MB
    max-request-size: 20MB
  datasource:
    url: jdbc:mysql://localhost:3306/fileupload?characterEncoding=utf-8&useSSL=false
    username: root
    password: Newworld0707
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.test.fileupload.model

#showSql
logging:
  level:
    com.test.fileupload.*: debug

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


prop:
  upload-folder: ./files

server.connectionTimeout : 80000
